export const openHeaderIdentifiers = [
  "TORNVIKEN - Vinhylla/Öppet väggskåp",
  "TORNVIKEN - Öppet väggskåp",
  "TORNVIKEN - Öppet bänkskåp/vinhylla/lådsektion D60",
  "TORNVIKEN - Bänkskåp öppen/vinhylla/hurts",
  "TORNVIKEN - Öppet bänkskåp D60",
  "TORNVIKEN - Bänkskåp öppen/vinhylla/hurts D60",
  "TORNVIKEN - Öppet bänkskåp/vinhylla/lådsektion",
  "TORNVIKEN - Öppet bänkskåp",
  "VADHOLMA - Vinhylla/Öppet väggskåp",
  "VADHOLMA - Öppet bänkskåp/Vinhylla/Lådsektion D60",
  "VADHOLMA - Bänkskåp öppen/vinhylla/hurts",
  "VADHOLMA - Bänkskåp öppen/vinhylla/hurts D60",
  "VADHOLMA - Öppet bänkskåp/Vinhylla/Lådsektion",
  "ENHET - högstomme m hyllplan, vit",
  "ENHET - högstomme m hyllplan, antracit",
  "ENHET - väggstomme m hyllplan, vit",
  "ENHET - väggstomme m hyllplan, antracit",
  "ENHET - väggstomme m hyllplan, antracit",
  "ENHET - väggstomme m hyllplan, vit",
  "ENHET - väggstomme med hyllplan, antracit",
  "ENHET - väggstomme med hyllplan, vit",
  "TITTEBO - jalusiförvaring f hushållsmaskiner, svart",
  "KNOXHULT - Wall Cabinet with Sliding Doors"
]