// app/coachPage/config/finalOptions.js

export const FINAL_OPTIONS = [
  "", // Tomt startalternativ
  "Snyggt jobbat! Du är bäst! 🌟👊",
  "Boom! Perfekt order från start till mål. Kör hårt! 💥🙌",
  "Riktigt snygg lösning! Kunden kommer bli supernöjd. 👏✨",
  "Magiskt bra! Inga frågetecken alls, bara att köra vidare! 💃☀️",
  "Kanonbra! Du har skapat ett både praktiskt och drömmigt kök! 🍽️✨",
  "Ren magi! Ordern är helt komplett och redo att skickas. Du äger! 💃🎉",
  "Spot on! Ordern ser riktigt bra ut och allt stämmer. Kör bara kör! 🚀💃",
  "En helt komplett order utan några konstigheter. Dansa vidare mot nästa kök! 💃🎶",
  "Superbra jobbat! Att rita kök är ett pussel, och du pusslar ihop det med glans. 🧩⭐🚀",
  "Wow, vilket snyggt jobb! Alla regler är följda till punkt och pricka. High five! 🖐️✨",
  "Snyggt jobbat! Du har verkligen öga för vad som skapar den där hemtrevliga wow-känslan. ✨☕😊",
  "Perfekt balans! Både designen och planeringsregler sitter som en smäck. Riktigt bra planerat! 📐✨",
  "Grymt jobbat! Det är en fröjd att se hur snabbt du tar till dig allt. 🚀👏",
  "Perfekt genomfört! Din känsla för planering blir bara bättre och bättre. Fortsätt så! 🚀👍",
  "Vilken utvecklingskurva! Du navigerar våra planeringsregler som om du inte gjort annat. 📈🙌",
  "Proffsigt! Det syns att du tänkt till en extra gång på alla funktioner. Fantastiskt jobbat! 💡👏",
  "Snyggt jobbat! Köksskissen ser helt fantastisk ut och alla artiklar finns med. Du börjar verkligen få kläm på det här! 💃🎉",
  "Strålande! Du planerar kök som ett riktigt proffs! 💃🌟",
  "Vilken superutveckling! 📈 Du lär dig i raketfart och ritar riktigt snygga kök. Superbra jobbat! 💃🎉",
  "Vilken stjärna! ⭐ Du plockar upp alla regler superfort och designen blev riktigt snygg. 👏",
  "Snabb OCH pricksäker! 🎯 Det går undan, men du tappar aldrig känslan för stil. Imponerande! 💃",
  "Riktig proffsklass! 🛠️ Du har lärt dig det här på nolltid och köket ser helt fantastiskt ut! 🌟",
  "Magisk känsla för form! 🎨 Du lär dig jättesnabbt och skapar så galet snygga lösningar. 👍",
  "Vilken inlärningskurva! 🚀 Det syns att du verkligen har fått kläm på det här. Snyggt pusslat! 🧩💃",
  "Full koll på läget! 💡 Du lär dig så snabbt att man knappt hinner med – och snyggt blir det också! 💃",
  "Superproffsigt! 📐 Du har hajat alla regler på nolltid och designen är verkligen spot on! ✨",
  "Vilken känsla! 👌 Du lär dig i supertempo och har ett fantastiskt öga för snygga detaljer. 🌟",
  "High five på den! 🖐️ Snabb inlärning och supersnyggt resultat. Kunden kommer älska det! 🎉",
  "Helt fantastiskt! 🌸 Du har förstått köksplaneringen direkt och skapar riktigt stilrena kök. 💃",
  "Det går som en dans! 💃 Du lär dig otroligt snabbt och levererar alltid så snygga ritningar! 🎶",
  "Klockren planering! 💡 Det syns att du lär dig snabbt – allt är snyggt, genomtänkt och rätt! 💃",
  "Vilket flyt du har fått! 🌊 Du snappar upp allt direkt och ritar otroligt snyggt. Bravo! 🎉",
  "Vilken talang! 🎨 Du har lärt dig allt på nolltid och skapar otroligt snygga kök. 💃✨",
  "Snabb som blixten, snyggt som tusen! ⚡🎨 Du har verkligen hittat flytet nu! 🎉",
  "Ren fröjd att se! 🌸 Du snappar upp reglerna direkt och designkänslan är på topp! 💃",
  "Vilken resa du gör! 🚀 Från ny till proffs på superkort tid – och så snyggt det blir! ⭐",
  "Klass på hög nivå! 🌟 Det går undan när du lär dig och resultatet blir stilrent och rätt! 📐",
  "Vilket öga du har! 👁️✨ Du tog till dig reglerna direkt och skapade ett riktigt drömkök. 💃",
  "Vilken stjärnskott! ⭐️ Snabb inlärning och supersnyggt resultat – du gör oss så stolta! 💃🎉",
  "Vilken fingertoppskänsla! 🤌 Du snappar upp allt i farten och ritar superfint. 🌟💃",
  "Snyggt ritat! Med de sista små ändringarna är detta projekt helt redo att göra kunden strålande glad. 🎉🍳✨",
  "Snabba ryck! ⚡ Några småfel slank med i farten. Rätta till så skickar vi! 💃",
  "Lugn & fin! 🛑 Du behärskar detta – låt det ta två minuter till så blir det rätt! ☕",
  "Nära ögat! 👀 Missade ett par småsaker i sprinten. Rätta till så kör vi! 🏃‍♂️",
  "Tappa inte noggrannheten i farten. Gör en sista check! 👍",
  "Ett djupt andetag! ☕ Du har full koll egentligen, kolla listan en gång till! ✨",
  "Paus & kolla! ☕ Riktigt bra grund, men det gick lite väl undan på slutet.",
  "Håll skärpan! 🔍 Du kan reglerna – gör en snabb sista-koll innan du skickar!",
  "Tänk två sekunder till! 💡 Grunden är super, men du stressade på slutet! 💃",
  "Ingen ko på isen! 🐄 Snygga bara till de sista så kör vi vidare!",
  "Dubbelkolla & gläns! 🌟 Du har full koll egentligen – gör bara en sista check!",
  "Nära perfektion! 👌 Snyggt ritat, men kika över artikellistan mer noggrant! 💃",
  "Slarvdjävulen slog till! 😈 Du har full koll egentligen, kolla igen! ✨",
  "Ett litet farthinder! 🛑 Snygg skiss, men farten kostade några artiklar.",
  "Kolla en gång till! 🔍 Du kan det här i sömnen – låt det bli rätt direkt! 💃",
  "Formen är där! 💪 Men det gick lite väl undan på slutet. Rätta till!",
  "Snabba puckar! 🏒 Glöm inte sista checklistan innan du trycker på klar!",
  "Släpp inte finessen! ✨ Du gör snygga kök, se till att artiklarna följer med!",
  "Tappa inte skärpan på upploppet! 🏁 Du kan detta utantill, svep över listan en sista gång!",
  "Ge det 30 sekunder till! ⏱️ Du behärskar reglerna, låt inte slarvfel förstöra en annars klockren order!",
  "Kör inte på autopilot! 🤖 Du har koll på läget, men stanna upp och dubbelkolla sista raderna. 💃",
  "Snabbt är bra, men rätt är bäst! ✨ Rätta till småmissarna så sätter vi den!",
  "Snygg ritning, men finliret saknas! 🎨 Du kan det här i sömnen – kika igenom tillbehören igen!",
  "Gör dig själv rättvisa! 💪 Du ritar superfint, så låt inte onödiga slarvfel smyga sig in. ☕",
  "Låt det inte gå på rutin! 🛠️ Grunden är kanon, men ta en extra titt på planeringsreglerna!",
  "Ett litet svep till! 🧹 Vi vet vad du går för – fixa de sista detaljerna så skickar vi! 🚀",
  "Sikta på 100%! 🎯 Tanken är helt rätt, men stressen gav några onödiga missar. Rätta till så kör vi! 💃",
  "Dra i handbromsen! 🚗💨 Du har full koll på hantverket, kika bara över täcksidor och mått en gång till.",
  "Slutfinishen saknas! 🖌️ Vi vet hur duktig du är – låt inte småfel slinka med i farten. 🌟",
  "Tumma inte på kvaliteten! 👍 Du kan reglerna utan och innan, stäm av en sista gång innan du trycker klart!"
];